version: '3'
services:
  web1:
    build:
      context: .
      dockerfile: Dockerfile.webserver
    volumes:
      - .:/usr/src/app
    ports:
      - "8080"

  web2:
    build:
      context: .
      dockerfile: Dockerfile.webserver
    volumes:
      - .:/usr/src/app
    ports:
      - "8080"

  loadbalancer:
    build:
      context: .
      dockerfile: Dockerfile.loadbalancer
    ports:
      - "80:80"
    links:
      - web1
      - web2

