FROM node:14

# Erstelle das Verzeichnis für die Anwendung im Container
WORKDIR /usr/src/app

# Installiere die Anwendungen
COPY package*.json ./
RUN npm install

# Bundle der Anwendungssource
COPY . .

# Der Container hört auf Port 8080
EXPOSE 8080
CMD [ "node", "app.js" ]

